# Generated by Django 6.0.5 on 2026-05-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('companies', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='edited_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('uploaded', 'Uploaded')], default='approved', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.CharField(default='system', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='emission_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionrecord'),
        ),
    ]
